-

diff --git a/commands/shell b/commands/shell
--- a/commands/shell
+++ b/commands/shell
@@ -86,13 +86,17 @@ then
     nix-env -iA cachix -f https://cachix.org/api/v1/install
 fi
 
-# FIXME: technially this will fail if the username contains regex chars
-if ! { cat /etc/nix/nix.conf | grep "trusted-users = \([^a]\|[a]\)*$(whoami)" 1>/dev/null; }
+# check if file exists
+if [ -f "/etc/nix/nix.conf" ]
 then
-    echo "Looks like you don't have yourself listed as a trusted user in /etc/nix/nix.conf"
-    echo "You can either add yourself and re-run this command"
-    echo "or enter your password below and I'll attempt to do it manually"
-    echo "trusted-users = root $(whoami)" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
+    # FIXME: technially this will fail if the username contains regex chars
+    if ! { cat /etc/nix/nix.conf | grep "trusted-users = \([^a]\|[a]\)*$(whoami)" 1>/dev/null; }
+    then
+        echo "Looks like you don't have yourself listed as a trusted user in /etc/nix/nix.conf"
+        echo "You can either add yourself and re-run this command"
+        echo "or enter your password below and I'll attempt to do it manually"
+        echo "trusted-users = root $(whoami)" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
+    fi
 fi
 
 export TMPDIR="/tmp" # fixes some build problems (workaround for a bug in Nix)
